name: Release
on:
  push:
    branches:
      - test-main
jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.github_tag_action.outputs.new_tag }}
      changelog: ${{ steps.github_tag_action.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: github_tag_action
        uses: mathieudutour/github-tag-action@331898d5052eedac9b15fec867b5ba66ebf9b692
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*
          default_bump: false

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build the IPFS bundle
        run: yarn build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # create_release:
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   needs: bump_version
  #   if: ${{ needs.bump_version.outputs.new_tag != null }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Set up node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://registry.npmjs.org

  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile

  #     - name: Build the IPFS bundle
  #       run: yarn build

  #     - name: Pin to Crust
  #       uses: crustio/ipfs-crust-action@v2.0.3
  #       continue-on-error: true
  #       timeout-minutes: 2
  #       with:
  #         cid: ${{ steps.upload.outputs.hash }}
  #         seeds: ${{ secrets.CRUST_SEEDS }}

  #     - name: Create GitHub Release
  #       id: create_release
  #       uses: actions/create-release@v1.1.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ needs.bump_version.outputs.new_tag }}
  #         release_name: Release ${{ needs.bump_version.outputs.new_tag }}
  #         body: |
  #           IPFS hash of the deployment:
  #           - CIDv0: `${{ steps.upload.outputs.hash }}`
  #           - CIDv1: `${{ steps.convert_cidv0.outputs.cidv1 }}`

  #           The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [app.uniswap.org](https://app.uniswap.org).

  #           You can also access the Uniswap Interface directly from an IPFS gateway.
  #           **BEWARE**: The Uniswap interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as which tokens you have imported.
  #           **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [app.uniswap.org](https://app.uniswap.org).
  #           Your Uniswap settings are never remembered across different URLs.

  #           IPFS gateways:
  #           - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.dweb.link/
  #           - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.cf-ipfs.com/
  #           - [ipfs://${{ steps.upload.outputs.hash }}/](ipfs://${{ steps.upload.outputs.hash }}/)

  #           ${{ needs.bump_version.outputs.changelog }}
